#define RELAY_FAN_PIN 2
#define RELAY_CIRCULATION_PIN 3
#define RELAY_HEATER_PIN 4
#define RELAY_LIGHT_PIN 5
#define RELAY_OZONE 6

#define BUTTON_ERASE_PIN 8
#define BUTTON_FEED_PIN 9
#define LDR_PIN A0
#define TEMPERATURE_PIN A1

#define NIGHT_LIGHT_PIN 7
#define FEEDER_PIN 11

#define VERSION 1

#define FLOAT_FORMAT 0.00f
#define EEPROM_MAX_VALUE 99.0
#define EEPROM_MIN_VALUE 0.0
#define EEPROM_MEM_POS1 0
#define EEPROM_MEM_POS2 4
#define EEPROM_MEM_POS3 8
#define EEPROM_MEM_POS4 12
#define EEPROM_MEM_POS5 16

